spring.application.name=minha-saude

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.banner-mode=off
spring.main.lazy-initialization=true
spring.jmx.enabled=false
server.tomcat.threads.max=10
spring.jackson.serialization.indent-output=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

server.port=${PORT:8080}